name: android-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown,aarch64-linux-android

      - name: Install Rust tools
        run: |
          cargo install --locked trunk
          cargo install --locked tauri-cli --version ^2.0.0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          ndk: 26.3.11579264
          cmake: 3.22.1

      - name: Configure Android project
        run: |
          cat <<PROP > src-tauri/gen/android/local.properties
          sdk.dir=$ANDROID_SDK_ROOT
          PROP
          if [ -z "${KEYSTORE_PASSWORD:-}" ]; then
            echo "Missing ANDROID_KEYSTORE_PASSWORD secret" >&2
            exit 1
          fi
          keytool -genkeypair -v \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEYSTORE_PASSWORD" \
            -keystore android-release.keystore \
            -alias upload \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=CI, OU=CI, O=CI, L=CI, S=CA, C=US"
          cat <<EOF > src-tauri/gen/android/keystore.properties
password=$KEYSTORE_PASSWORD
keyAlias=upload
storeFile=${PWD}/android-release.keystore
EOF

      - name: Build release APK (arm64)
        working-directory: src-tauri/gen/android
        run: ./gradlew assembleRelease -PtargetList=aarch64 -ParchList=arm64 -PabiList=arm64-v8a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-release-apk
          path: src-tauri/gen/android/app/build/outputs/apk/**/*.apk
